### ISSUE TITLE
Race condition causes test failure under parallel testing

### ISSUE THREAD

**Issue by kentfredric** [petdance/file-next#16]
http://www.cpantesters.org/cpan/report/61a8fe24-4936-11e3-b097-b376ba4edfeb 

Easiest way to replicate this:

``` bash
$ perl Makefile.PL
$ make
$ prove -bvrj2 t/everything.t t/follow.t
```

Essentially the flaw is multiple tests augment the same directory simultaneously, and then get confused by each others changes.

Though I don't think this is the only combination that causes a failure, just its the easiest to find.

**Comment by petdance** [comment]
See #17 for a specific test we know needs to use a temp dir.

**Comment by petdance** [comment]
Anybody have a patch for this handy?

**Comment by petdance** [comment]
Fixed with 0f2d2dc298b4ac339a3b2d198208014c4c814c36 and releasing in 1.13_02.

**Comment by karenetheridge** [comment]
Awesome, thank you!

**Comment by petdance** [comment]
Have you tried your Mac OS X battery of tests?

**Comment by petdance** [comment]
Have you tried your Mac OS X battery of tests?  I'm not seeing any at http://matrix.cpantesters.org/?dist=File-Next

**Comment by petdance** [comment]
Looks like you did your batch of darwin tests at http://matrix.cpantesters.org/?dist=File-Next, so I'm guessing you're OK with a release at this point.

**Comment by karenetheridge** [comment]
👍
