### ISSUE TITLE
Calling POSIX::tmpnam() is deprecated at t/named-pipe.t line 13.

### ISSUE THREAD

**Issue by toddr** [petdance/file-next#23]
In perl 5.22, POSIX::tmpnam is deprecated.

https://metacpan.org/pod/distribution/perl/ext/POSIX/lib/POSIX.pod

```
tmpnam
Returns a name for a temporary file.

$tmpfile = POSIX::tmpnam();

For security reasons, which are probably detailed in your system's documentation for the C library tmpnam() function, this interface should not be used; instead see File::Temp.
```

**Comment by toddr** [comment]
It looks like all you're trying to do in the code is to make a temp file. Pull request pending.

**Comment by karenetheridge** [comment]
As of perl 5.25.1, this interface has been removed, and tests now fail.

**Comment by ap** [comment]
Last commit was 09c0c7ba4858932addbc14c855f1bde3b7539b0c on `dev`, from Jan 2014, a year and a half before this ticket – incidentally about the very same issue this ticket is about, though motivated by Android, so #24 is even redundant. But last CPAN release is from Dec 2012, so that fix never made it out. PAUSE says the only permission on File::Next is first-come for PETDANCE.

@petdance?

**Comment by petdance** [comment]
I'm releasing 1.13_01 in a little bit.

**Comment by petdance** [comment]
The uploaded file

   File-Next-1.13_01.tar.gz

has entered CPAN as

 file: $CPAN/authors/id/P/PE/PETDANCE/File-Next-1.13_01.tar.gz
 size: 17241 bytes
  md5: 132451f274a888e78851a849274d3a04
 sha1: 851de386589e2454a7d71441fd1969d08aedc26e

CPAN Testers will start reporting results in an hour or so:

 http://matrix.cpantesters.org/?dist=File-Next

Request entered by: PETDANCE (Andy Lester)
Request entered on: Tue, 31 May 2016 02:48:40 GMT
Request completed:  Tue, 31 May 2016 02:48:43 GMT

**Comment by petdance** [comment]
Are y'all satisfied with the changes, @karenetheridge & @ap?  Can I release 1.14?

**Comment by karenetheridge** [comment]
Have you looked at the cpantesters reports? I reported at least a few failures a few days ago, across different perl versions.

**Comment by petdance** [comment]
My bad.  I was only seeing failures on 1.12 on the page, but now that I sift through the settings properly, now I'm seeing the failures.  http://www.cpantesters.org/distro/F/File-Next.html?grade=3&perlmat=2&patches=2&oncpan=2&distmat=3&perlver=ALL&osname=ALL&version=1.13_01

They seem to be all OS X.  I haven't dug into it yet, but any obvious suggestions as to why they're failing?

**Comment by petdance** [comment]
These failures seem to be #16 and #17.

**Comment by karenetheridge** [comment]
Agreed, the tests pass on perl 5.25.1 with `HARNESS_OPTIONS=j1`.

**Comment by petdance** [comment]
The uploaded file

   File-Next-1.13_02.tar.gz

has entered CPAN as

 file: $CPAN/authors/id/P/PE/PETDANCE/File-Next-1.13_02.tar.gz
 size: 17621 bytes
  md5: c0665ecc2cc3f09825254b2f506b7d05
 sha1: 1dc5257825bfe823fa2bb18146e796c9bc896ef2

CPAN Testers will start reporting results in an hour or so:

 http://matrix.cpantesters.org/?dist=File-Next

Request entered by: PETDANCE (Andy Lester)
Request entered on: Mon, 06 Jun 2016 04:24:54 GMT
Request completed:  Mon, 06 Jun 2016 04:25:15 GMT

Thanks,
-- 
paused, v1049
